### PR TITLE
read file before processing it

### PR DESCRIPTION
**Pull request by ftyers**
The dictionary reading code was reading the filename as the data, this patch reads the data. :)

### CODE REVIEW

**Comment by foxik** [comment]
As documented at https://ufal.mff.cuni.cz/udpipe/users-manual#model_training , all option values can be either strings, or `file:filename`, in case the data is read from the filename, or `data:length:value`. Therefore, if you want to read the dictionary from file, just use `dictionary=file:filename`.

I think it would be inconsistent with other options to specify filename for the `dictionary`.

**Comment by foxik** [comment]
BTW, the loading happens in https://github.com/ufal/udpipe/blob/master/src/utils/named_values.h#L58

**Comment by ftyers** [comment]
Thanks for looking at this. We should have read the docs in more detail. Would it be possible to update the docs to read:

```
dictionary (default empty): use given custom morphological dictionary (specify 
filename using file:), where every line contains 5 tab-separated fields FORM, 
LEMMA, UPOSTAG, XPOSTAG and FEATS. Note that this dictionary data is 
appended to the dictionary created from UD training data, not replacing it. 
```

Also, would it be possible to throw an error message if the user does not use `file:` ?

**Comment by foxik** [comment]
The inclusion of embedding is different because it is difficult to pass the data directly (one of the UDPipe components expect the embeddings to be in a file).

So it is difficult for me to do `embedding_form=file:`. However, as the dictionary will be in file anyway, I will implement the `dictionary_file=` variant. However, I will get to it only after the shared task :-)

**Comment by ftyers** [comment]
I've moved this to issue #36 and will close the PR.

**Pull request closed without merging**
